#!/usr/local/bin/python3.4

## This script updates the CUSIP -- Ticker dictionary mannually
##  and removes the CUSIP from CUSIP Ignore list when applicable
## The CUSIP -- Ticker dictionary and the CUSIP Ignore list are
##  generated by the 13FCUSIPs script which screens the 13F filings of funds
##  and look for tickers using CUSIP at the Fidelity website
## But the website may fail to return a ticker for a proper CUSIP number

import csv


def SaveDict2CSV(filename, datDict):
    with open(filename, 'w', encoding='utf-8') as csvfile:
        writer = csv.writer(csvfile)
        for key, value in datDict.items():
            writer.writerow([key, value])

def SaveSet2CSV(filename, datSet):
    ##print(datSet)
    datTmp = list(datSet)
    ##print(datTmp)
    with open(filename, 'w', encoding='utf-8') as csvfile:
        writer=csv.writer(csvfile)
        for line in datTmp :
            writer.writerow([line])

fileCUSIPTicker = '/Users/Shared/Models/CUSIPTicker.csv'
try:
    with open(fileCUSIPTicker, mode='rt') as csvfile:
        dictCUSIPTicker = dict(csv.reader(csvfile))
except Exception as e:
    print(e)
    dictCUSIPTicker = dict()

fileCUSIPIgnore = '/Users/Shared/Models/CUSIPIgnore.csv'
try:
    with open(fileCUSIPIgnore, mode='rt') as csvfile:
        CUSIPIgnore = set([row[0] for row in csv.reader(csvfile)])
except Exception as e:
    print(e)
    CUSIPIgnore = set()


newCUSIPTickerList = [('06759L103', 'BBDC'),
                      ('50015M109', 'KOD'),
                      ('78464A954', 'SPTL'),
                      ('78464A950', 'BIL'),
                      ('464287955', 'IWM'),
                      ('158990812', 'CSBR'),
                      ('559663109', 'MGY'),
                      ('58933Y905', 'MRK'),
                      ('03965L900', 'ARNC'),
                      ('03836N103', 'APTX'),
                      ('722304102', 'PDD'),
                      ('46122W105', 'INUV'),
                      ('30607B109', 'FLMN'),
                      ('98422L107', 'XERS'),
                      ('70387R106', 'PAVM'),
                      ]

ignoreCUSIPs = ['803607142']


CUSIPIgnore = CUSIPIgnore.union(set(ignoreCUSIPs))

newCUSIPTicker = dict(newCUSIPTickerList)

print(newCUSIPTicker)

dictCUSIPTickerUpdated = False
CUSIPIgnoreUpdated = True
for key in newCUSIPTicker:
    if dictCUSIPTicker:
        if key in dictCUSIPTicker:
            if (dictCUSIPTicker[key] != newCUSIPTicker[key]):
                print(key + ' exists with a different ticker: '+dictCUSIPTicker[key]+ ' instead of '+ newCUSIPTicker[key])
                continue
            else:
                continue
        else:
            dictCUSIPTicker[key] = newCUSIPTicker[key]
            dictCUSIPTickerUpdated = True
    else:
        dictCUSIPTicker[key] = newCUSIPTicker[key]
        dictCUSIPTickerUpdated = True

    if CUSIPIgnore:
        if key in CUSIPIgnore:
            CUSIPIgnore.remove(key)
            CUSIPIgnoreUpdated = True

for key in dictCUSIPTicker:
    if CUSIPIgnore:
        if key in CUSIPIgnore:
            CUSIPIgnore.remove(key)
            CUSIPIgnoreUpdated = True

if dictCUSIPTickerUpdated:
    SaveDict2CSV(fileCUSIPTicker, dictCUSIPTicker)

if CUSIPIgnoreUpdated:
    SaveSet2CSV(fileCUSIPIgnore, CUSIPIgnore)
    
            

